<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Price (excl. GST)_radiobutton_0</name>
   <tag></tag>
   <elementGuidId>a444ff46-a960-47cc-8afc-0f872faac4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radiobutton_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radiobutton_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#radiobutton_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d35f5c67-0efc-4179-ac94-1dfd8ebef8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>b5e7ddec-d098-4655-814e-8aa1954b3301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>eff0f6f0-58de-44ed-9f22-c74407864233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a17e5238-fb1f-4ee8-abef-bbd4dc9f2c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60115c3f-c442-4b96-9852-335b9041d2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radiobutton_0&quot;)</value>
      <webElementGuid>33861ef4-e990-401e-89cf-ebacab2f9523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radiobutton_0']</value>
      <webElementGuid>26b7aa72-d4c6-4bb9-a3f8-ae5a370c3ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>8171db99-e3f7-48ee-be6a-9164fcfc157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a2e85a7b-87a3-40f4-947a-b9ce8dd9f0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radiobutton_0' and @id = 'radiobutton_0' and @type = 'radio']</value>
      <webElementGuid>b168cbf7-35a3-4aa6-84f1-91c829e76a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
