<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cc_cvv</name>
   <tag></tag>
   <elementGuidId>2fad9094-ef07-4c4d-b995-8bd66ef98fbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc_cvv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cc_cvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cc_cvv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa20da13-c78a-4b6f-b094-b16e8382f167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_cvv</value>
      <webElementGuid>954854e4-2c02-4aae-bf4f-9f3acafea966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7599726-596b-4bbe-9d99-40c33820ec6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_input</value>
      <webElementGuid>8026d91f-8934-4185-bfe1-106f09220397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_cvv</value>
      <webElementGuid>a15dac96-96ab-49d1-929a-91363fe6c4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>702fe5a5-ef59-48e0-a280-98c4dfca7098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return OnlyNumbersonly(event)</value>
      <webElementGuid>74acc17c-5dcd-416a-ac4c-22682e60b99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_cvv&quot;)</value>
      <webElementGuid>1cf3829d-a642-4d57-848a-3f0813db9e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cc_cvv']</value>
      <webElementGuid>c1d2a0bb-d606-4288-bead-750738297d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[18]/td[2]/input</value>
      <webElementGuid>ad87127f-e212-4404-9cba-d42070cc54ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/input</value>
      <webElementGuid>2b1acd86-e22d-4950-a39f-2d5c1d95ca0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cc_cvv' and @type = 'text' and @id = 'cc_cvv']</value>
      <webElementGuid>cd6271ba-b08d-4eb0-8347-025ec469df78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
