<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Select Month -            January _3505f5</name>
   <tag></tag>
   <elementGuidId>afabfbfa-f332-467c-9a8a-ed39eef0cf48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cc_exp_month</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>15181347-f100-4657-8e4c-ae6695ee7da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>4de9fa6c-13b9-4abb-a0cc-8c694d30e643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>466e7b8c-9adc-4a52-819b-5a3fbd1fd61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>8f219330-e1a1-498d-9d50-7e79cfbf8abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          </value>
      <webElementGuid>c0183312-1942-48ca-9f19-bb4c0537083d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_month&quot;)</value>
      <webElementGuid>a976230d-b11f-44d3-8299-3d158dfcb86d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_month']</value>
      <webElementGuid>13259021-e06f-4334-95d2-f66a2a740119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select</value>
      <webElementGuid>0931e090-24cd-458f-b7db-5e7a03bac9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>3eb9ec5b-2c07-4308-b6ad-8423e7619e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[2]</value>
      <webElementGuid>16945cac-0889-4c45-8ce4-28bbb138ac8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/select</value>
      <webElementGuid>5fe69796-9c26-4d6a-8e88-5c6bd474042f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_month' and @id = 'cc_exp_month' and (text() = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ' or . = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ')]</value>
      <webElementGuid>300ded0a-3c1a-4d09-b8df-9e79ac778384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
