<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order No_my_itinerary</name>
   <tag></tag>
   <elementGuidId>0632e5d2-f9a6-42cd-b6c8-9d17ef6197b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='my_itinerary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#my_itinerary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e6a6a1a-2284-4621-a08d-af27875cebbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3c7b7a4-3da2-4b28-9c25-acd164271064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>my_itinerary</value>
      <webElementGuid>61e67167-bd49-4e75-bbe1-8831e6905004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>my_itinerary</value>
      <webElementGuid>d6390829-60e2-4031-ac3d-b5e057281dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>48315ba6-c18e-4798-8593-a0f11423bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>My Itinerary</value>
      <webElementGuid>920efc5e-d9f1-4145-ae0f-31b27cf8d213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location=&quot;BookedItinerary.php&quot;</value>
      <webElementGuid>fcbc0d61-faf1-4aa9-8bcc-a97958a4a7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my_itinerary&quot;)</value>
      <webElementGuid>1d388945-896a-4ef0-92f8-f18aeed52a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='my_itinerary']</value>
      <webElementGuid>e3fd99bf-2873-4932-a325-0f5d8d060609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booking_form']/table/tbody/tr[19]/td[2]/input[2]</value>
      <webElementGuid>4f1bb9b5-dfde-4d35-b039-d795a4aad5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>2741e810-c9c7-4252-bba8-04e85a5270c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'my_itinerary' and @id = 'my_itinerary']</value>
      <webElementGuid>568adabb-f983-4a41-ae5f-a62cd2ae68c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
