<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Order No</name>
   <tag></tag>
   <elementGuidId>5060ab6c-3ed6-45d2-8dae-3ee71f0a8e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(18) > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='booking_form']/table/tbody/tr[18]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Order No.&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3299ccae-bb03-445d-99a6-4121c1310e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>02f78ff0-1844-4820-8808-6f96804a4b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order No.    </value>
      <webElementGuid>8d0a3a5e-a141-4404-97be-891f71775081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_form&quot;)/table[@class=&quot;login&quot;]/tbody[1]/tr[18]/td[1]</value>
      <webElementGuid>82573ce3-ac08-4004-8d78-82c876505fad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booking_form']/table/tbody/tr[18]/td</value>
      <webElementGuid>8aade198-27f8-41b1-8de5-1a3caa7fd8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Westmead'])[1]/following::td[1]</value>
      <webElementGuid>48bd6c39-ac2a-4440-bf6d-7c370fe85698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adactin.com'])[1]/preceding::td[5]</value>
      <webElementGuid>8cc8d6ac-60e2-4c88-8e46-bf37332ab686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td</value>
      <webElementGuid>76d20759-1dda-446e-b59c-9bf3d53ecc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Order No.    ' or . = 'Order No.    ')]</value>
      <webElementGuid>3fa7277d-8384-4d15-b330-5f3f6c2697d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
